#!/bin/sh -l
#SBATCH --partition=Apus
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=120:00:00
#SBATCH --mem-per-cpu=4G

export OMP_NUM_THREADS=1

# Pass ncpu and nstep from the prompt
NCPU=$SLURM_CPUS_PER_TASK
NSTEP=$1
TAG=${NSTEP}-${NCPU}

echo "Running on node: $(hostname)"
echo "Job ID: $SLURM_JOB_ID"
echo "Job Name: $SLURM_JOB_NAME"
echo "CPUS_PER_TASK=${NCPU}, NSTEP=${NSTEP}, TAG=${TAG}"

python ntest.py --ncpu ${NCPU} --steps ${NSTEP} --dir ${TAG} > log-${TAG} 

# Usage
# sbatch -J N10-S100 -c 10 myrun 100
# sbatch -J N8-S100 -c 8 myrun 100
